name: Pokemon Watcher

on:
  schedule:
    - cron: "*/10 * * * *" # Läuft jetzt alle 10 Minuten
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # WICHTIG: Erlaubt dem Bot, die state.json wieder hochzuladen

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4

      - name: Run watcher
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}        
        run: python watcher.py # Führt deine watcher.py aus

      - name: Commit state.json
        run: |
          git config user.name github-actions
          git config user.email actions@github.com

          git add state.json

          # Wenn sich nichts geändert hat, bricht das Skript nicht ab
          git diff --cached --quiet || git commit -m "Update state"

          git push
