name: Pokemon Watcher

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write # WICHTIG: Erlaubt dem Bot, die state.json wieder hochzuladen

    steps:
      - uses: actions/checkout@v4

        # Python auf dem GitHub-Server einrichten
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

        # Benötigte Python-Bibliotheken installieren
      - name: Install packages
        run: |
          pip install requests beautifulsoup4

        # Den Bot ausführen
      - name: Run watcher
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}        
        run: python watcher.py # Führt deine watcher.py aus

        # Den neuen Zustand der state.json wieder sicher auf GitHub abspeichern
      - name: Commit state.json
        run: |
          git config user.name github-actions
          git config user.email actions@github.com

          git add state.json

          # Wenn sich nichts geändert hat, bricht das Skript nicht ab
          git diff --cached --quiet || git commit -m "Update state"

          git push
